### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by GXSZone** [kelinZhou/PhotoSelector#3]
PhotoSelectorActivity可以写到自己的库里面降低集成步骤，打包的时候清单合并是一样的。
这一块也可以放库里
```
<provider
            android:name=".provider.PictureFileProvider"
            android:authorities="${applicationId}.SelectorProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/selector_provider_paths" />
        </provider>
```
新建个类自定义FileProvider
```
 class PictureFileProvider : FileProvider() {

}  
```
`<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <queries>
        <package android:name="com.huawei.camera" />

        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.media.action.VIDEO_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.provider.action.PICK_IMAGES" />
        </intent>
    </queries>
    <application>

        <activity
            android:name="com.kelin.photoselector.PhotoSelectorActivity"
            android:configChanges="screenSize|orientation" />

        <provider
            android:name=".provider.PictureFileProvider"
            android:authorities="${applicationId}.SelectorProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/selector_provider_paths" />
        </provider>

    </application>
</manifest>
`

**Comment by kelinZhou** [comment]
最早都是放在库里的，后来发现如果想自定义会有冲突。
